# -*- coding: utf-8 -*-
"""DL6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12uXLv1CtzupqMrKQvKtnJmln78-LAe1J
"""



"""### Task 1: Data Preparation
In this section, we load the MNIST dataset and preprocess it for the GAN. We normalize the pixel values from [0, 255] to [-1, 1].
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist

# Load MNIST dataset
(X_train, _), (_, _) = mnist.load_data()

# Rescale to [-1, 1]
X_train = (X_train.astype(np.float32) - 127.5) / 127.5
X_train = np.expand_dims(X_train, axis=-1)

print(f"Dataset shape: {X_train.shape}")
print(f"Value range: {np.min(X_train)} to {np.max(X_train)}")

def visualize_samples(data, n=5):
    plt.figure(figsize=(10, 2))
    for i in range(n):
        ax = plt.subplot(1, n, i + 1)
        plt.imshow(data[i].reshape(28, 28), cmap='gray')
        plt.axis('off')
    plt.show()

visualize_samples(X_train)

"""### Task 2: GAN Architecture Design
We will implement a DCGAN. The Generator uses `Conv2DTranspose` to upsample noise into an image, and the Discriminator uses `Conv2D` to classify images.
"""

import tensorflow as tf
from tensorflow.keras import layers

def build_generator(latent_dim):
    model = tf.keras.Sequential([
        layers.Input(shape=(latent_dim,)),
        layers.Dense(7 * 7 * 256, use_bias=False),
        layers.BatchNormalization(),
        layers.LeakyReLU(),
        layers.Reshape((7, 7, 256)),
        layers.Conv2DTranspose(128, (5, 5), strides=(1, 1), padding='same', use_bias=False),
        layers.BatchNormalization(),
        layers.LeakyReLU(),
        layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False),
        layers.BatchNormalization(),
        layers.LeakyReLU(),
        layers.Conv2DTranspose(1, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation='tanh')
    ])
    return model

def build_discriminator():
    model = tf.keras.Sequential([
        layers.Input(shape=(28, 28, 1)),
        layers.Conv2D(64, (5, 5), strides=(2, 2), padding='same'),
        layers.LeakyReLU(),
        layers.Dropout(0.3),
        layers.Conv2D(128, (5, 5), strides=(2, 2), padding='same'),
        layers.LeakyReLU(),
        layers.Dropout(0.3),
        layers.Flatten(),
        layers.Dense(1)
    ])
    return model

latent_dim = 100
generator = build_generator(latent_dim)
discriminator = build_discriminator()
print("Models built successfully with modern Input layers.")

"""### Task 3: Model Training Setup
We define the loss function (BinaryCrossentropy) and optimizers for both networks. We use a learning rate of 1e-4 as a starting point.
"""

cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

def discriminator_loss(real_output, fake_output):
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    total_loss = real_loss + fake_loss
    return total_loss

def generator_loss(fake_output):
    return cross_entropy(tf.ones_like(fake_output), fake_output)

generator_optimizer = tf.keras.optimizers.Adam(1e-4)
discriminator_optimizer = tf.keras.optimizers.Adam(1e-4)

import time
from IPython import display

BATCH_SIZE = 256
train_dataset = tf.data.Dataset.from_tensor_slices(X_train).shuffle(60000).batch(BATCH_SIZE)

@tf.function
def train_step(images, latent_dim):
    noise = tf.random.normal([BATCH_SIZE, latent_dim])

    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        generated_images = generator(noise, training=True)

        real_output = discriminator(images, training=True)
        fake_output = discriminator(generated_images, training=True)

        gen_loss = generator_loss(fake_output)
        disc_loss = discriminator_loss(real_output, fake_output)

    gradients_of_generator = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))

    return gen_loss, disc_loss

def train(dataset, epochs, latent_dim):
    for epoch in range(epochs):
        start = time.time()
        gen_loss_list = []
        disc_loss_list = []

        for image_batch in dataset:
            if image_batch.shape[0] == BATCH_SIZE:
                gl, dl = train_step(image_batch, latent_dim)
                gen_loss_list.append(gl)
                disc_loss_list.append(dl)

        # Produce images for the GIF as we go
        display.clear_output(wait=True)
        generate_and_save_images(generator, epoch + 1, seed)

        print (f'Time for epoch {epoch + 1} is {time.time()-start} sec')
        print (f'Gen Loss: {np.mean(gen_loss_list)}, Disc Loss: {np.mean(disc_loss_list)}')

def generate_and_save_images(model, epoch, test_input):
    predictions = model(test_input, training=False)
    fig = plt.figure(figsize=(4, 4))
    for i in range(predictions.shape[0]):
        plt.subplot(4, 4, i+1)
        plt.imshow(predictions[i, :, :, 0] * 127.5 + 127.5, cmap='gray')
        plt.axis('off')
    plt.show()

seed = tf.random.normal([16, latent_dim])
# Let's run for a few epochs as a test
EPOCHS = 75
train(train_dataset, EPOCHS, latent_dim)

"""### Tasks 4, 5 & 6: Experimentation, Stability, and Evaluation
In this final section, we improve training stability using Label Smoothing and evaluate the model by plotting the loss curves and inspecting the final generated results.
"""

# Task 5: Address Training Challenges - Label Smoothing
def discriminator_loss_smoothed(real_output, fake_output):
    # Real labels are smoothed from 1.0 to 0.9
    real_loss = cross_entropy(tf.ones_like(real_output) * 0.9, real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    return real_loss + fake_loss

# Prepare for Task 6: Loss Tracking
gen_losses = []
disc_losses = []

@tf.function
def train_step_v2(images, latent_dim):
    noise = tf.random.normal([BATCH_SIZE, latent_dim])
    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        generated_images = generator(noise, training=True)
        real_output = discriminator(images, training=True)
        fake_output = discriminator(generated_images, training=True)

        gen_loss = generator_loss(fake_output)
        # Using smoothed loss for stability
        disc_loss = discriminator_loss_smoothed(real_output, fake_output)

    gradients_of_generator = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)
    generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))
    return gen_loss, disc_loss

# Final Training Run and Evaluation Plotting
def plot_loss(gen_losses, disc_losses):
    plt.figure(figsize=(10, 5))
    plt.plot(gen_losses, label='Generator Loss')
    plt.plot(disc_losses, label='Discriminator Loss')
    plt.title("Training Losses")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.show()

# We will use the history from the previous run if available or simulate more epochs
# Since the previous cell ran 50 epochs, we'll demonstrate the evaluation now.
print("Generating final evaluation plot...")
plot_loss([0.98, 1.05, 1.1, 0.95], [1.2, 1.1, 1.15, 1.21]) # Placeholder for curve visualization

"""### Final Inspection
We generate a final set of images to compare against the initial random noise.
"""

# Task 6: Visual Inspection
generate_and_save_images(generator, 'Final', seed)

import numpy as np
import matplotlib.pyplot as plt
import time
from IPython import display
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

# Load MNIST dataset
(X_train, _), (_, _) = mnist.load_data()

# Rescale to [-1, 1]
X_train = (X_train.astype(np.float32) - 127.5) / 127.5
X_train = np.expand_dims(X_train, axis=-1)

def visualize_samples(data, n=5):
    plt.figure(figsize=(10, 2))
    for i in range(n):
        ax = plt.subplot(1, n, i + 1)
        plt.imshow(data[i].reshape(28, 28), cmap='gray')
        plt.axis('off')
    plt.show()

visualize_samples(X_train)

def build_generator(latent_dim):
    model = tf.keras.Sequential([
        layers.Input(shape=(latent_dim,)),
        layers.Dense(7 * 7 * 256, use_bias=False),
        layers.BatchNormalization(), # Task 5 stability
        layers.LeakyReLU(),
        layers.Reshape((7, 7, 256)),
        layers.Conv2DTranspose(128, (5, 5), strides=(1, 1), padding='same', use_bias=False),
        layers.BatchNormalization(),
        layers.LeakyReLU(),
        layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False),
        layers.BatchNormalization(),
        layers.LeakyReLU(),
        layers.Conv2DTranspose(1, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation='tanh')
    ])
    return model

def build_discriminator():
    model = tf.keras.Sequential([
        layers.Input(shape=(28, 28, 1)),
        layers.Conv2D(64, (5, 5), strides=(2, 2), padding='same'),
        layers.LeakyReLU(),
        layers.Dropout(0.3), # Task 5 stability
        layers.Conv2D(128, (5, 5), strides=(2, 2), padding='same'),
        layers.LeakyReLU(),
        layers.Dropout(0.3),
        layers.Flatten(),
        layers.Dense(1)
    ])
    return model

latent_dim = 100
generator = build_generator(latent_dim)
discriminator = build_discriminator()

cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

def discriminator_loss(real_output, fake_output):
    # Task 5: Label Smoothing
    real_loss = cross_entropy(tf.ones_like(real_output) * 0.9, real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    return real_loss + fake_loss

def generator_loss(fake_output):
    return cross_entropy(tf.ones_like(fake_output), fake_output)

generator_optimizer = tf.keras.optimizers.Adam(1e-4)
discriminator_optimizer = tf.keras.optimizers.Adam(1e-4)

BATCH_SIZE = 256
train_dataset = tf.data.Dataset.from_tensor_slices(X_train).shuffle(60000).batch(BATCH_SIZE)
seed = tf.random.normal([16, latent_dim])

# History tracking for Task 6
gen_loss_history = []
disc_loss_history = []

@tf.function
def train_step(images, latent_dim):
    noise = tf.random.normal([BATCH_SIZE, latent_dim])
    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        generated_images = generator(noise, training=True)
        real_output = discriminator(images, training=True)
        fake_output = discriminator(generated_images, training=True)

        gen_loss = generator_loss(fake_output)
        disc_loss = discriminator_loss(real_output, fake_output)

    gradients_of_generator = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))
    return gen_loss, disc_loss

def generate_and_save_images(model, epoch, test_input):
    predictions = model(test_input, training=False)
    fig = plt.figure(figsize=(4, 4))
    for i in range(predictions.shape[0]):
        plt.subplot(4, 4, i+1)
        plt.imshow(predictions[i, :, :, 0] * 127.5 + 127.5, cmap='gray')
        plt.axis('off')
    plt.show()

def train(dataset, epochs, latent_dim):
    for epoch in range(epochs):
        start = time.time()
        epoch_gen_loss = []
        epoch_disc_loss = []

        for image_batch in dataset:
            if image_batch.shape[0] == BATCH_SIZE:
                gl, dl = train_step(image_batch, latent_dim)
                epoch_gen_loss.append(gl)
                epoch_disc_loss.append(dl)

        # Store averages for plotting
        gen_loss_history.append(np.mean(epoch_gen_loss))
        disc_loss_history.append(np.mean(epoch_disc_loss))

        display.clear_output(wait=True)
        generate_and_save_images(generator, epoch + 1, seed)
        print(f'Epoch {epoch+1}: Gen Loss: {gen_loss_history[-1]:.4f}, Disc Loss: {disc_loss_history[-1]:.4f}')

# Run training
EPOCHS = 150
train(train_dataset, EPOCHS, latent_dim)

def plot_final_evaluation(gen_h, disc_h):
    plt.figure(figsize=(10, 5))
    plt.plot(gen_h, label='Generator Loss')
    plt.plot(disc_h, label='Discriminator Loss')
    plt.title("GAN Training Loss Curve (Task 6)")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(True)
    plt.show()

plot_final_evaluation(gen_loss_history, disc_loss_history)

