# -*- coding: utf-8 -*-
"""DL_Assignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vYxtbM_EusDWIOHtpi5JolaorLg6EaZG
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import warnings, sys
warnings.filterwarnings("ignore")

from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers, Input
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, confusion_matrix,
                             ConfusionMatrixDisplay, classification_report)

# ── Hyperparameters ──
VOCAB_SIZE    = 10000
MAX_LEN       = 256
EMBEDDING_DIM = 64
BATCH_SIZE    = 64
EPOCHS        = 10
RNN_UNITS     = 64

"""### Load IMDB dataset — built into Keras, no download needed"""

(X_train_full, y_train_full), (X_test, y_test) = imdb.load_data(num_words=VOCAB_SIZE)

# Pad / Truncate to fixed length
X_train_full = pad_sequences(X_train_full, maxlen=MAX_LEN, padding='post', truncating='post')
X_test       = pad_sequences(X_test,       maxlen=MAX_LEN, padding='post', truncating='post')

# 90/10 stratified train-validation split
X_train, X_val, y_train, y_val = train_test_split(
    X_train_full, y_train_full,
    test_size=0.1, random_state=42, stratify=y_train_full
)

print(f"Train      : {X_train.shape}")
print(f"Validation : {X_val.shape}")
print(f"Test       : {X_test.shape}")
print(f"Label dist (train) — Positive: {y_train.sum()}  Negative: {(1-y_train).sum()}")

def plot_training_curves(history, model_name):
    h  = history.history
    ep = range(1, len(h['accuracy']) + 1)

    fig, axes = plt.subplots(1, 2, figsize=(13, 4))
    fig.suptitle(f"{model_name} — Training Curves", fontsize=13, fontweight='bold')

    axes[0].plot(ep, h['accuracy'],     label='Train Acc',  marker='o', color='steelblue')
    axes[0].plot(ep, h['val_accuracy'], label='Val Acc',    marker='s', color='darkorange')
    axes[0].set_title("Accuracy")
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Accuracy")
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    axes[1].plot(ep, h['loss'],     label='Train Loss', marker='o', color='steelblue')
    axes[1].plot(ep, h['val_loss'], label='Val Loss',   marker='s', color='crimson')
    axes[1].set_title("Loss")
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Loss")
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(f"{model_name}_training_curves.png", dpi=150, bbox_inches='tight')
    plt.show()

def evaluate_model(model, model_name):
    print(f"\n{'='*55}")
    print(f"  EVALUATION: {model_name}")
    print(f"{'='*55}")

    y_prob = model.predict(X_test, verbose=0).flatten()
    y_pred = (y_prob > 0.5).astype(int)

    acc  = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec  = recall_score(y_test, y_pred)
    f1   = f1_score(y_test, y_pred)
    cm   = confusion_matrix(y_test, y_pred)

    # ── Metrics ──
    print(f"\n  Accuracy  : {acc:.4f}")
    print(f"  Precision : {prec:.4f}")
    print(f"  Recall    : {rec:.4f}")
    print(f"  F1-Score  : {f1:.4f}")

    # ── Classification Report ──
    print(f"\n  Classification Report:")
    print(classification_report(y_test, y_pred,
                                target_names=['Negative', 'Positive']))

    # ── Confusion Matrix Plot ──
    fig, ax = plt.subplots(figsize=(5, 4))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                                   display_labels=['Negative', 'Positive'])
    disp.plot(ax=ax, colorbar=False, cmap='Blues')
    ax.set_title(f"{model_name} — Confusion Matrix", fontsize=12, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f"{model_name}_confusion_matrix.png", dpi=150, bbox_inches='tight')
    plt.show()

    return {'accuracy': acc, 'precision': prec, 'recall': rec, 'f1': f1}

# Store all results for final comparison
all_results = {}

"""### Defining Model Architecture"""

print("=" * 55)
print("  MODEL 1: SimpleRNN (Baseline)")
print("=" * 55)

model_rnn = Sequential([
    Input(shape=(MAX_LEN,)),                              # ← explicit Input layer (dtype fix)
    layers.Embedding(input_dim=VOCAB_SIZE,
                     output_dim=EMBEDDING_DIM,
                     mask_zero=True),
    layers.SimpleRNN(units=RNN_UNITS, activation='tanh',
                     return_sequences=False),
    layers.Dropout(0.3),
    layers.Dense(32, activation='relu'),
    layers.Dense(1,  activation='sigmoid')
], name='SimpleRNN_Model')

model_rnn.summary()

model_rnn.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

callbacks_rnn = [
    EarlyStopping(monitor='val_loss', patience=3,
                  restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                      patience=3, min_lr=1e-6, verbose=1)
]

history_rnn = model_rnn.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=callbacks_rnn,
    verbose=1
)

plot_training_curves(history_rnn, "SimpleRNN")

all_results['SimpleRNN'] = evaluate_model(model_rnn, "SimpleRNN")

print("=" * 55)
print("  MODEL 2: LSTM (Long Short-Term Memory)")
print("=" * 55)

model_lstm = Sequential([
    layers.Embedding(VOCAB_SIZE, EMBEDDING_DIM,
                     input_length=MAX_LEN, mask_zero=True),
    layers.LSTM(units=RNN_UNITS, dropout=0.2, recurrent_dropout=0.2,
                return_sequences=False),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.BatchNormalization(),
    layers.Dense(1,  activation='sigmoid')
], name='LSTM_Model')

model_lstm.summary()

model_lstm.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

callbacks_lstm = [
    EarlyStopping(monitor='val_loss', patience=3,
                  restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                      patience=3, min_lr=1e-6, verbose=1)
]

history_lstm = model_lstm.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=callbacks_lstm,
    verbose=1
)

plot_training_curves(history_lstm, "LSTM")

all_results['LSTM'] = evaluate_model(model_lstm, "LSTM")

print("=" * 55)
print("  MODEL 3: GRU (Gated Recurrent Unit)")
print("=" * 55)

model_gru = Sequential([
    layers.Embedding(VOCAB_SIZE, EMBEDDING_DIM,
                     input_length=MAX_LEN, mask_zero=True),
    layers.GRU(units=RNN_UNITS, dropout=0.2, recurrent_dropout=0.2,
               return_sequences=False),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.Dense(1,  activation='sigmoid')
], name='GRU_Model')

model_gru.summary()

model_gru.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

callbacks_gru = [
    EarlyStopping(monitor='val_loss', patience=3,
                  restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                      patience=3, min_lr=1e-6, verbose=1)
]

history_gru = model_gru.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=callbacks_gru,
    verbose=1
)

plot_training_curves(history_gru, "GRU")

all_results['GRU'] = evaluate_model(model_gru, "GRU")

print("=" * 55)
print("  MODEL 4: Bidirectional LSTM")
print("=" * 55)

model_bilstm = Sequential([
    layers.Embedding(VOCAB_SIZE, EMBEDDING_DIM,
                     input_length=MAX_LEN, mask_zero=True),
    layers.Bidirectional(
        layers.LSTM(units=RNN_UNITS, dropout=0.2, recurrent_dropout=0.2,
                    return_sequences=False),
        merge_mode='concat'
    ),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.BatchNormalization(),
    layers.Dense(1, activation='sigmoid')
], name='Bidirectional_LSTM_Model')

model_bilstm.summary()

model_bilstm.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

callbacks_bilstm = [
    EarlyStopping(monitor='val_loss', patience=3,
                  restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                      patience=3, min_lr=1e-6, verbose=1)
]

history_bilstm = model_bilstm.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=callbacks_bilstm,
    verbose=1
)

plot_training_curves(history_bilstm, "Bidirectional_LSTM")

all_results['Bidirectional_LSTM'] = evaluate_model(model_bilstm, "Bidirectional_LSTM")

print("=" * 55)
print("  MODEL 5: Bidirectional GRU")
print("=" * 55)

model_bigru = Sequential([
    layers.Embedding(VOCAB_SIZE, EMBEDDING_DIM,
                     input_length=MAX_LEN, mask_zero=True),
    layers.Bidirectional(
        layers.GRU(units=RNN_UNITS, dropout=0.2, recurrent_dropout=0.2,
                   return_sequences=False),
        merge_mode='concat'
    ),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')
], name='Bidirectional_GRU_Model')

model_bigru.summary()

model_bigru.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

callbacks_bigru = [
    EarlyStopping(monitor='val_loss', patience=5,
                  restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                      patience=3, min_lr=1e-6, verbose=1)
]

history_bigru = model_bigru.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=callbacks_bigru,
    verbose=1
)

plot_training_curves(history_bigru, "Bidirectional_GRU")